baseURL: "https://roshangthomas.github.io/"
languageCode: "en-us"
title: "Roshan's Website"
theme: "hugo-profile"
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      url: "blog/"

  # home
  disable_home: false
  profile_image: images/logo.jpeg
  name: "Roshan Thomas"
  namecolor: ffc107
  profession: "Student, UC Berkeley"
  github: "https://github.com"
  gitlab: "https://gitlab.com"
  linkedin: "https://linkedin.com/in/roshangthomas"
  twitter: "https://twitter.com/roshangthomas"
  instagram: "https://instagram.com/roshangthomas"
  facebook: "https://facebook.com"

  # Custom social links
  customSocialLinks:
    - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
      url: "https://gohugo.com"
    - fontAwesomeIconName: "fa fa-envelope"
      url: "https://gmail.com"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Profile, a passionate web developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "This is a example template for about section. You can find my works [here](#projects)"
  skills:
    - name: Python
      percentage: 90
    - name: Java
      percentage: 85
    - name: C
      percentage: 70
    - name: React JS
      percentage: 60

  # Experience
  disable_experience: false
  experience:
    - company: "Google"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "BS"
      branch: "Electrical Engineering and Computer Science"
      university: "UC Berkeley"
      startedyear: "2020"
      graduation: "2024"
    - degree: "BS"
      branch: "Business Administration"
      university: "UC Berkeley (Haas)"
      startedyear: "2020"
      graduation: "2024"
    - degree: "Diploma"
      university: "University High School"
      startedyear: "2016"
      graduation: "2020"

  # Projects
  disable_projects: false
  projects:
    - name: "Project Whitestone"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Trading Algorithm"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll get back to you shortly!
  email: "roshanthomas@berkeley.edu"

  # Footer
  socialiconfooter: false
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
